// Code generated by scripts/gen-ssr-modules.ts — DO NOT EDIT.
// Run `pnpm generate` to regenerate after adding/removing pages.

import type { Component } from 'vue'
import Home from './pages/Home.vue'

const modules: Record<string, Component> = {
  'Home': Home,
}

export default modules
