// Code generated by `goapp gen`. DO NOT EDIT.
//
// MountAll wires every non-admin controller area onto the engine; the generator
// rewrites the gen:mounts block as resources are added or removed. Admin is
// wired separately in serve.go.
package controller

import (
	"github.com/millken/goapp-template/internal/app"
	"github.com/millken/goapp-template/internal/controller/site"
	"github.com/millken/inertia"
)

// MountAll registers all generated controller areas. Route uniqueness is
// enforced by inertia at registration time.
func MountAll(eng *inertia.Engine, svc *app.Services) {
	// gen:mounts:begin
	site.Mount(eng, svc)
	// gen:mounts:end
}
