#!/usr/bin/env tsx
/**
 * Generates both:
 *   - ssr-modules.ts          (SSR sync imports for QuickJS)
 *   - src/inertia/modules.ts  (client-side lazy imports for Vite)
 *
 * Run: pnpm generate
 */

import fs from 'node:fs'
import path from 'node:path'

const pagesDir = path.resolve('./pages')

if (!fs.existsSync(pagesDir)) {
  console.error('Error: pages/ directory not found')
  process.exit(1)
}
function collectVueFiles(dir: string, base = dir): string[] {
  const result: string[] = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      result.push(...collectVueFiles(full, base))
    } else if (entry.name.endsWith('.vue')) {
      result.push(path.relative(base, full).replace(/\\/g, '/'))
    }
  }
  return result.sort()
}

/** "fund/index.vue" → "FundIndex" */
function toCamelCase(file: string): string {
  return file
    .replace(/\.vue$/, '')
    .split(/[/_-]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('')
}

/** "fund/index.vue" → "fund/index" */
function toKey(file: string): string {
  return file.replace(/\.vue$/, '')
}

const files = collectVueFiles(pagesDir)

// --- ssr-modules.ts ---
const ssrImports = files
  .map((f) => `import ${toCamelCase(f)} from './pages/${f}'`)
  .join('\n')

const ssrEntries = files
  .map((f) => `  '${toKey(f)}': ${toCamelCase(f)},`)
  .join('\n')

const ssrContent = `// Code generated by scripts/gen-ssr-modules.ts — DO NOT EDIT.
// Run \`pnpm generate\` to regenerate after adding/removing pages.

import type { Component } from 'vue'
${ssrImports}

const modules: Record<string, Component> = {
${ssrEntries}
}

export default modules
`

// --- src/inertia/modules.ts ---
const clientEntries = files
  .map((f) => `  '${toKey(f)}': () => import('../../pages/${f}'),`)
  .join('\n')

const clientContent = `// Code generated by scripts/gen-ssr-modules.ts — DO NOT EDIT.
// Run \`pnpm generate\` to regenerate after adding/removing pages.

import type { Component } from 'vue'

export const modules: Record<string, () => Promise<Component>> = {
${clientEntries}
}
`

fs.writeFileSync(path.resolve('./ssr-modules.ts'), ssrContent)
fs.writeFileSync(path.resolve('./src/inertia/modules.ts'), clientContent)
console.log(`Generated ${files.length} page${files.length === 1 ? '' : 's'}: ssr-modules.ts, src/inertia/modules.ts`)
