-- 004_user_status.up.sql
-- Whether an admin user may sign in and hold a session. 1 = active, 0 = disabled.
--
-- No backfill statement: a constant DEFAULT on ADD COLUMN fills existing rows,
-- so every user that predates this migration lands active. 003 needed an
-- explicit UPDATE only because its group_id was nullable and therefore left
-- existing rows unusable — do not copy that pattern here.
--
-- SQLite flavor (the template's default driver). PostgreSQL and MySQL accept
-- this statement as written.
--
-- This migration writes the literal `users` table. The [admin] users_table
-- setting redirects runtime lookups only — embedded SQL cannot read config — so
-- pointing it elsewhere makes that table's schema the operator's
-- responsibility, including this column.
ALTER TABLE users ADD COLUMN status INTEGER NOT NULL DEFAULT 1;
