// Code generated by scripts/gen-ssr-modules.ts — DO NOT EDIT.
// Run `pnpm generate` to regenerate after adding/removing pages.

import type { Component } from 'vue'

export const modules: Record<string, () => Promise<Component>> = {
  'Home': () => import('../../pages/Home.vue'),
}
