-- 006_admin_avatar.up.sql (MySQL)
-- The admin's avatar as a path relative to the storage root, or '' for none.
-- A path, not a URL: the public prefix is config (storage.url_prefix), and
-- baking it into stored data would make changing it a data migration.
--
-- Not wrapped in a goappctl marker, unlike the Go and Vue code that uses it: a
-- column nobody writes to is harmless, while a conditionally-numbered migration
-- would make two generated projects disagree about what 006 is.
--
-- VARCHAR, not TEXT, so the DEFAULT '' is legal here. 512 is the ceiling on
-- this dialect; storage paths are relative to the root, so it is generous.
--
-- No backfill: a constant DEFAULT on ADD COLUMN fills existing rows.
ALTER TABLE admins ADD COLUMN avatar VARCHAR(512) NOT NULL DEFAULT '';
